trigger:
  - main

resources:
  - repo: self

stages:
  - stage: Test
    displayName: Run Tests
    jobs:
      - job: Test
        displayName: Test
        pool:
          vmImage: "windows-latest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Install Node.js"

          - script: npm install
            displayName: "Install dependencies"

          - script: npm run test:ci
            displayName: "Run unit tests"

          - script: npm run test-storybook:ci
            displayName: "Run component tests"

          - task: PublishTestResults@2
            displayName: "Supply test results to pipelines"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "*.xml"
              mergeTestResults: true

  - stage: Build
    displayName: Build and Push
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              containerRegistry: "frontend-template-connection"
              repository: "samples/frontend-template"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: "latest"

  - stage: Restart
    displayName: Restart Web App
    jobs:
      - job: Restart
        displayName: Restart
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: "Pay-As-You-Go (0beee491-5b30-485e-94e2-07cd165984df)"
              Action: "Restart Azure App Service"
              WebAppName: "frontend-template"
