trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "Install dependencies"

  - script: npm run test:ci
    displayName: "Run unit tests"

  - script: npm run test-storybook:ci
    displayName: "Run component tests"

  - task: PublishTestResults@2
    displayName: "Supply test results to pipelines"
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "*.xml"
      mergeTestResults: true

  - task: Docker@2
    inputs:
      containerRegistry: "frontendtemplate"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
